# Generated by Django 4.1.2 on 2022-10-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('place', models.EmailField(max_length=254)),
                ('email', models.CharField(max_length=8)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
    ]
